if not table.containsId then
	dofile("Scripts/mods.lua")
end
local dkjson = require "dkjson"

local foulbornMods = LoadModule("../Data/ModFoulborn.lua")
local queryMods = LoadModule("../Data/QueryMods.lua")
launch.versionNumber = "alpha"
main.POESESSID = "" -- Not sure if this is needed for this query
LoadModule("../Classes/TradeQueryRateLimiter")

local function appendModMapToFile(modMap)
	local out = io.open("../Data/ModFoulbornMap2.lua", "a")
	for itemName, modLists in pairs(modMap) do
		out:write('\b\t["', itemName, '"] = {\n') -- \b is a backspace character to remove the closing brace, then we re-add it after in case this is the last call
		for _, modList in ipairs(modLists) do
			out:write('\t\t{\n')
			out:write('\t\t\texplicits = { ')
			for mod, _ in pairs(modList.explicits) do
				out:write('["', mod, '"] = true, ')
			end
			out:write('},\n')
			out:write('\t\t\tmutated = "', modList.mutated, '",\n')
			out:write('\t\t},\n')
		end
		out:write('\t},\n}')
	end
	out:close()
end

local out = io.open("../Data/ModFoulbornMap2.lua", "r")
if false then
	out:close()
else
	print("Foulborn mod map not found, generating new map...")
	out = io.open("../Data/ModFoulbornMap2.lua", "w")
	out:write('-- This file is automatically generated, do not edit!\n')
	out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
	out:close()

	LoadModule("../Classes/TradeQueryRequests")
	local tradeQueryRequester = new("TradeQueryRequests")
	tradeQueryRequester.maxFetchPerSearch = 1

	local mutatedModMap = { }
	local count = 0
	for id, entry in pairsSortByKey(foulbornMods) do
		count = count + 1
		if count > 1 then break end
		for _, order in ipairs(entry.statOrder) do
			if queryMods["Explicit"][order .. "_" .. entry.group] then
				local queryEntry = queryMods["Explicit"][order .. "_" .. entry.group]
				local queryTable = {
					query = {
						filters = {
							type_filters = {
								filters = {
									mutated = {
										option = "true"
									},
								}
							}
						},
						status = { option = "any" },
						stats = {
							{
								type = "and",
								filters = { { id = "explicit.stat_" .. entry.tradeHash, value = { weight = (queryEntry.invert == true and queryEntry.weight * -1 or queryEntry.weight) } } }
							}
						}
					},
					engine = "new"
				}

				local queryJson = dkjson.encode(queryTable)
				tradeQueryRequester:SearchWithQuery("pc", "Standard", queryJson, function(results, errMsg)
					if errMsg then
						print("Error fetching trade data for mod '" .. id .. "': " .. errMsg)
						return
					end
					if results and results[1] then
						print("Fetched trade data for mod '" .. id .. "': " .. results[1].name)
						local itemMap = {
							["explicits"] = { },
							["mutated"] = id
						}
						for _, hashTbl in ipairs(results[1].explicitHashes) do
							itemMap.explicits[hashTbl[1]] = true
						end
						if mutatedModMap[results[1].name] then
							table.insert(mutatedModMap[results[1].name], itemMap)
						else
							mutatedModMap[results[1].name] = { itemMap }
						end
					end
					appendModMapToFile(mutatedModMap)
				end)
				main.onFrameFuncs["TradeQueryRequests"] = function()
					tradeQueryRequester:ProcessQueue()
				end
			end
		end
	end
end