-- if not table.containsId then
-- 	dofile("Scripts/mods.lua")
-- end
local dkjson = require "dkjson"

local foulbornMods = LoadModule("../Data/ModFoulborn.lua")
local finalUniqueMap = { }
local mappedMods = { }

local function fetchStats()
	local tradeStats = ""
	local easy = common.curl.easy()
	easy:setopt_url("https://www.pathofexile.com/api/trade/data/stats")
	easy:setopt_useragent("Path of Building/" .. launch.versionNumber)
	easy:setopt_writefunction(function(data)
		tradeStats = tradeStats..data
		return true
	end)
	easy:perform()
	easy:close()
	return tradeStats
end


local out = io.open("../Data/ModFoulbornMap2.lua", "r")
if false then
    out:close()
else
    print("Foulborn mod map not found, generating new map...")
    out = io.open("../Data/ModFoulbornMap2.lua", "w")
    -- originates from: https://www.pathofexile.com/api/trade/data/stats
    local tradeStats = fetchStats()
    tradeStats:gsub("\n", " ")
    local tradeQueryStatsParsed = dkjson.decode(tradeStats)

    LoadModule("../Classes/TradeQueryGenerator")
    local tradeQueryGenerator = new("TradeQueryGenerator")
    tradeQueryGenerator.modData = { ["Foulborn"] = { } }
    tradeQueryGenerator:GenerateModData(foulbornMods, tradeQueryStatsParsed)

    -- out:write('-- This file is automatically generated, do not edit!\n')
    -- out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
    out:write('[\n')
    LoadModule("../Classes/TradeQueryRequests")
    local tradeQueryRequester = new("TradeQueryRequests")
    tradeQueryRequester.maxFetchPerSearch = 1

    for id, entry in pairs(tradeQueryGenerator.modData["Foulborn"]) do
        local queryTable = {
            query = {
                filters = {
                    type_filters = {
                        filters = {
                            mutated = {
                                option = "true"
                            },
                        }
                    }
                },
                status = { option = "any" },
                stats = {
                    {
                        type = "and",
                        filters = { { id = entry.tradeModId, value = { weight = (entry.invert == true and entry.weight * -1 or entry.weight) } } }
                    }
                }
            },
            sort = { ["statgroup.0"] = "desc" },
            engine = "new"
        }

        local queryJson = dkjson.encode(queryTable)
        tradeQueryRequester:SearchWithQuery("pc", "Standard", queryJson, function(results, errMsg)
            if errMsg then
                print("Error fetching trade data for mod '" .. id .. "': " .. errMsg)
                return
            end
            local resultsLua = dkjson.decode(results)
            if resultsLua and resultsLua.result and #resultsLua.result > 0 then
                local item = resultsLua.result[1].item
                out:write(dkjson.encode(item), ",\n")
            end
        end)
    end

    out:write(']\n')
    out:close()
end