-- if not table.containsId then
-- 	dofile("Scripts/mods.lua")
-- end
local dkjson = require "dkjson"

local foulbornMods = LoadModule("../Data/ModFoulborn.lua")
local queryMods = LoadModule("../Data/QueryMods.lua")
launch.versionNumber = "alpha"
main.POESESSID = ""
-- LoadModule("../Data/Global")
-- LoadModule("../Modules/ItemTools")
LoadModule("../Classes/TradeQueryRateLimiter")

local finalUniqueMap = { }
local mappedMods = { }

-- local function fetchStats()
-- 	local tradeStats = ""
-- 	local easy = common.curl.easy()
-- 	easy:setopt_url("https://www.pathofexile.com/api/trade/data/stats")
-- 	easy:setopt_useragent("Path of Building/" .. launch.versionNumber)
-- 	easy:setopt_writefunction(function(data)
-- 		tradeStats = tradeStats..data
-- 		return true
-- 	end)
-- 	easy:perform()
-- 	easy:close()
-- 	return tradeStats
-- end


local function appendModMapToFile(modMap, file)
    local out = io.open("../Data/ModFoulbornMap2.lua", "a")
    for itemName, modLists in pairs(modMap) do
        out:write('\t["', itemName, '"] = {\n')
        for _, modList in ipairs(modLists) do
            out:write('\t\t{\n')
            out:write('\t\t\texplicits = { ')
            for mod, _ in pairs(modList.explicits) do
                out:write('["', mod, '"] = true, ')
            end
            out:write('},\n')
            out:write('\t\t\tmutated = { ')
            for _, mod in ipairs(modList.mutated) do
                out:write('"', mod, '", ')
            end
            out:write('},\n')
            out:write('\t\t},\n')
        end
        out:write('\t},\n')
    end
    out:close()
end

local out = io.open("../Data/ModFoulbornMap2.lua", "r")
if false then
    out:close()
else
    print("Foulborn mod map not found, generating new map...")
    out = io.open("../Data/ModFoulbornMap2.lua", "w")
    -- -- originates from: https://www.pathofexile.com/api/trade/data/stats
    -- local tradeStats = fetchStats()
    -- tradeStats:gsub("\n", " ")
    -- local tradeQueryStatsParsed = dkjson.decode(tradeStats)
    -- tradeQueryStatsParsed.localResults = { }
	-- for modTypeId, modType in ipairs(tradeQueryStatsParsed.result) do
	-- 	tradeQueryStatsParsed.localResults[modTypeId] = { label = modType.label, entries = { } }
	-- 	for modId, mod in ipairs(modType.entries) do
	-- 		if mod.text:match("(Local)") then
	-- 			tradeQueryStatsParsed.localResults[modTypeId].entries[modId] = mod
	-- 		end
	-- 	end
	-- end

    -- LoadModule("../Classes/TradeQueryGenerator")
    -- local tradeQueryGenerator = new("TradeQueryGenerator", {}, false)
    -- tradeQueryGenerator.modData = { ["Explicit"] = { } }
    -- tradeQueryGenerator:GenerateModData(foulbornMods, tradeQueryStatsParsed)

    out:write('-- This file is automatically generated, do not edit!\n')
    out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
    LoadModule("../Classes/TradeQueryRequests")
    local tradeQueryRequester = new("TradeQueryRequests")
    tradeQueryRequester.maxFetchPerSearch = 1

    local mutatedModMap = { }
    local count = 0
    for id, entry in pairs(foulbornMods) do
        count = count + 1
        if count > 1 then break end
        for _, order in ipairs(entry.statOrder) do
            if queryMods["Explicit"][order .. "_" .. entry.group] then
                local queryEntry = queryMods["Explicit"][order .. "_" .. entry.group]
                local queryTable = {
                    query = {
                        filters = {
                            type_filters = {
                                filters = {
                                    mutated = {
                                        option = "true"
                                    },
                                }
                            }
                        },
                        status = { option = "any" },
                        stats = {
                            {
                                type = "and",
                                filters = { { id = queryEntry.tradeMod.id, value = { weight = (queryEntry.invert == true and queryEntry.weight * -1 or queryEntry.weight) } } }
                            }
                        }
                    },
                    engine = "new"
                }

                local queryJson = dkjson.encode(queryTable)
                tradeQueryRequester:SearchWithQuery("pc", "Standard", queryJson, function(results, errMsg)
                    if errMsg then
                        print("Error fetching trade data for mod '" .. id .. "': " .. errMsg)
                        return
                    end
                    if results and results[1] then
                        print("Fetched trade data for mod '" .. id .. "': " .. results[1].name)
                        local itemMap = {
                            ["explicits"] = {},
                            ["mutated"] = results[1].mutatedMods
                        }
                        for _, mod in ipairs(results[1].explicitMods) do
                            itemMap.explicits[mod] = true
                        end
                        if mutatedModMap[results[1].name] then
                            table.insert(mutatedModMap[results[1].name], itemMap)
                        else
                            mutatedModMap[results[1].name] = { itemMap }
                        end
                    end
                    appendModMapToFile(mutatedModMap, out)
                end)
                main.onFrameFuncs["TradeQueryRequests"] = function()
                    tradeQueryRequester:ProcessQueue()
                end
            end
        end
    end
    out:close()
end