-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Foulborn Unnatural Instinct"] = {
		{
			explicits = { ["Allocated Small Passive Skills in Radius grant nothing"] = true, },
			mutated = { "Grants all bonuses of Unallocated Notable Passive Skills in Radius", },
		},
	},
