-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Foulborn The Aylardex"] = {
		{
			explicits = { ["explicit.stat_2262736444"] = true, ["explicit.stat_1050105434"] = true, ["explicit.stat_3872306017"] = true, ["explicit.stat_227523295"] = true, ["explicit.stat_1325047894"] = true, ["explicit.stat_2847548062"] = true, ["explicit.stat_2102212273"] = true, },
			mutated = "MutatedUniqueAmluet24EldritchBattery",
		},
	},
}