name: Run Tests
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "luajit-2.0.5"
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Install busted
        run: luarocks install busted
      - name: Install cluacov
        run: luarocks install cluacov
      - name: Unzip for lua libs
        run: unzip runtime-win32.zip
      - name: Set LUA_PATH
        run: echo "LUA_PATH=$LUA_PATH;$GITHUB_WORKSPACE/lua/?.lua" >> $GITHUB_ENV
      - name: Run tests
        run: busted -c --lua=/home/runner/work/PathOfBuilding/PathOfBuilding/.lua/bin/luajit --helper=HeadlessWrapper.lua .
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
