name: Run Tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "luajit-2.0.5"
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Install busted
        run: luarocks install busted
      - name: Install cluacov
        run: luarocks install cluacov
      - name: Install coveralls integration
        run: luarocks install luacov-coveralls
      - name: Unzip for lua libs
        run: unzip runtime-win32.zip
      - name: Set LUA_PATH
        run: export LUA_PATH=./lua/?.lua
      - name: Run tests
        run: busted -c --lua=/usr/bin/luajit --helper=HeadlessWrapper.lua .
      - name: Report coverage
        run: luacov-coveralls
